### ISSUE TITLE
Not working with SSR

### ISSUE THREAD

**Issue by kije** [amrlabib/react-timer-hook#29]
I'm trying to use this with Gatsby.js, but the problem is the UMD wrapper that is generated in the dist folder is referencing window, which breaks the build because `window` is not defined during SSR.

The best way to fix this/increase compatibility would be to generate builds for multiple targets (see https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953).

Another, quicker approach might be to include the `src/` files in the npm package and reference the `src/index.js` via the `"module"` property in `package.json`

see also:
- https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953
- https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules

**Comment by dwilt** [comment]
Can we get this looked at being merged? Breaking in our Gatsby project, too.

**Comment by amrlabib** [comment]
@kije thank you for the issue and sorry for the late response, i found this [solution](https://github.com/webpack/webpack/issues/6784#issuecomment-375941431) on a similar issue reported on webpack repo

I think it is an issue in how webpack is bundling the code, the solution will change the global object to point to `this` which will be based on environment (browser or server) because ideally UMD should work on both browser and server without any issues.

This should be fixed now in the latest v2.0.3 i hope it will work now with SSR
