### ISSUE TITLE
useStopwatch hook is causing continuous rerender

### ISSUE THREAD

**Issue by aravifrog** [amrlabib/react-timer-hook#67]
Hi! I'm using this library for making user session time out. For that, I'm using useStopwatch hook.

`const { hours, pause, reset } = useStopwatch({ autoStart: true }); `

But these causes render to the application every second. Is there a better way to achieve it or I'm implementing it wrong?

**Comment by Pluto8195** [comment]
This hook will cause a rerender in whatever component your using it in by nature of it "ticking" every second to give you an accurate time

If its causing your entire app to rerender is likey because it is somewere high in your component structure,
I tried wrapping useStopwatch in a custom hook but was also getting parent component rerenders the simplest solution I've found is to create a function child and pass a function you want to call when your timeout condition is met

```javascript
import React, { useEffect } from 'react'
import { useStopwatch } from 'react-timer-hook'


// This Component will Rerender every second
const TimeOut = ({ onTimeout }) => {
  const { hours, seconds, pause, reset } = useStopwatch({ autoStart: true }); 
  
  useEffect(() => {
    // Some condition to match current hours to timeout
    if(seconds === 7) {
      onTimeout()
    }
  }, [seconds])

  return null
}


// Component should only render once
const Component = () => {
  
  const handleTimeout = () => console.log('TIMEOUT')

  return (
    <div>
      <TimeOut onTimeout={handleTimeout}/>
    </div>
  )
}


export default Component
```

**Comment by aravifrog** [comment]
I'm using `useStopwatch` right now in `App.tsx.`. I wrapped `useStopwatch` inside a component as you suggested and it avoids the re-renders for other components. Thank you for your suggestion and appreciate it!
